# Description:
# gtl subtle packages.

load("//third_party/tensorflow:tensorflow.default.bzl", "filegroup")

package(
    licenses = ["notice"],
)

filegroup(
    name = "map_traits",
    srcs = [
        "map_traits.h",
    ],
    visibility = [
        "//third_party/tensorflow/core/lib/gtl/subtle:__pkg__",
        "//tsl/lib/gtl:__pkg__",
    ],
)
