package_group(
    name = "friends",
    includes = ["//tsl:internal"],
)

package_group(
    name = "internal",
    packages = [
        "//third_party/tensorflow/core/profiler/...",
        "//third_party/tensorflow/python/eager/...",
        "//third_party/tensorflow/python/profiler/...",
        "//third_party/tensorflow/python/tpu/profiler/...",
        "//tsl/profiler/...",
    ],
)
